apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q319mcneq-python 
  janus-idp.io/tekton: q319mcneq-python
  backstage.io/kubernetes-id: q319mcneq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q319mcneq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml